# MediaMTX Configuration for Neolink
# This configuration enables the HTTP API required by Neolink for health checks
# and configures path publishing to accept RTSP streams from FFmpeg.

###############################################
# API Configuration (REQUIRED for Neolink)
###############################################

# Enable HTTP API for Neolink health checks and monitoring
api: yes
apiAddress: :9997

###############################################
# RTSP Server Configuration
###############################################

# Enable RTSP server
rtsp: yes

# RTSP server listening address
rtspAddress: :8554

# List of enabled RTSP transport protocols
# TCP is most reliable for Docker/NAT environments
rtspTransports: [tcp]

###############################################
# Path Configuration
###############################################

# Accept RTSP publishing from Neolink/FFmpeg
# The "all_others" path matches any stream path (e.g., /CameraName/main, /CameraName/sub)
paths:
  all_others:
    # Source: publisher means MediaMTX will accept incoming RTSP streams
    # from Neolink/FFmpeg and make them available to clients
    source: publisher

    # Allow any client to read streams (no authentication)
    # If you want authentication, uncomment and set these:
    # readUser: viewer
    # readPass: password

    # Allow local publishers (Neolink/FFmpeg) without authentication
    # If you want to restrict publishing, uncomment and set these:
    # publishUser: neolink
    # publishPass: secret

###############################################
# Logging
###############################################

# Log level: debug, info, warn, error
logLevel: info

# Log destinations: stdout, file
logDestinations: [stdout]

###############################################
# Performance Tuning
###############################################

# Read timeout for client connections
readTimeout: 10s

# Write timeout for client connections
writeTimeout: 10s

# Size of the queue of outgoing packets
# Higher value = more throughput, lower value = less RAM
writeQueueSize: 512

###############################################
# Optional: Additional Protocols
###############################################

# RTMP server (for OBS, etc.)
rtmp: yes
rtmpAddress: :1935

# HLS server (for web browsers)
hls: yes
hlsAddress: :8888
hlsAlwaysRemux: no
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms

# WebRTC server (for web browsers)
webrtc: yes
webrtcAddress: :8889
webrtcICEServers2: []

# SRT server
srt: yes
srtAddress: :8890
